project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "notebooks/*.ipynb"
    - "!MIGRATION*.md"
    - "!PROJECT_STRUCTURE.md"
    - "!LATEX_PACKAGES.md"
    - "!check_migration.sh"
    - "!finish_migration.sh"
    - "!migrate_content.sh"
    - "!NOTEBOOK_FIXES.md"
    - "!fix_notebook_paths.py"
    - "!verify_notebook_assets.py"
    - "!update_tex_files.sh"

website:
  title: "ES335: Machine Learning"
  description: "Machine Learning course at IIT Gandhinagar - comprehensive materials with interactive notebooks and lecture slides"
  favicon: images/logo.jpeg
  navbar:
    background: white
    logo: images/logo.jpeg
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      - href: tutorials.qmd
        text: Tutorials
      - href: notebooks.qmd
        text: Notebooks
    right:
      - href: https://nipunbatra.github.io
        text: Instructor
        target: _blank
  sidebar: false
  page-footer:
    left: |
      ES335: Machine Learning  
      IIT Gandhinagar
    center: |
      Copyright 2025
    right: |
      [Quarto](https://quarto.org/) | [Instructor](https://nipunbatra.github.io)
    background: light

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: github
    mainfont: "Inter, system-ui, sans-serif"
    monofont: "JetBrains Mono, SF Mono, Monaco, monospace"
    code-copy: true
    code-overflow: wrap
    code-fold: false
    code-tools: false
    toc: true
    toc-location: right
    toc-depth: 3
    smooth-scroll: true
    link-external-newwindow: true
    fig-responsive: true
    
  # Notebook-specific formatting
  ipynb:
    theme:
      light: [cosmo, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: github
    mainfont: "Inter, system-ui, sans-serif"
    monofont: "JetBrains Mono, SF Mono, Monaco, monospace"
    code-copy: true
    code-overflow: wrap
    code-fold: false
    code-tools: false
    toc: true
    toc-location: right
    toc-depth: 3
    embed-resources: false
    fig-width: 8
    fig-height: 6
    fig-dpi: 300
    smooth-scroll: true
    link-external-newwindow: true
    fig-responsive: true

execute:
  freeze: true
  echo: true
  warning: false
  error: false
  cache: true
  
jupyter:
  kernelspec:
    display_name: "Python 3"
    language: python
    name: python3
