project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "notebooks/*.ipynb"
    - "!MIGRATION*.md"
    - "!PROJECT_STRUCTURE.md"
    - "!LATEX_PACKAGES.md"
    - "!check_migration.sh"
    - "!finish_migration.sh"
    - "!migrate_content.sh"

website:
  title: "Machine Learning Course"
  description: "Comprehensive machine learning course materials with interactive notebooks and lecture slides"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      - href: notebooks.qmd
        text: Notebooks
    right:
      - href: https://nipunbatra.github.io
        text: Instructor
  sidebar: false
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)"
    right: "Course by [Nipun Batra](https://nipunbatra.github.io)"

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom-dark.scss]
    highlight-style: github
    mainfont: "Inter"
    code-copy: true
    code-overflow: wrap
    code-fold: true
    code-tools: true
    toc: true
    toc-location: right
    toc-depth: 3
    
  # Notebook-specific formatting
  ipynb:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom-dark.scss]
    highlight-style: github
    mainfont: "Inter"
    code-copy: true
    code-overflow: wrap
    code-fold: false
    code-tools: true
    toc: true
    toc-location: right
    toc-depth: 3
    embed-resources: false
    fig-width: 8
    fig-height: 6
    fig-dpi: 300

execute:
  freeze: auto
  echo: true
  warning: false
  error: false
  
jupyter:
  kernelspec:
    display_name: "Python 3"
    language: python
    name: python3
