on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches:
      - master
      - main

name: Build & Deploy ML Course Materials

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Cache Jupyter kernels
        uses: actions/cache@v3
        with:
          path: ~/.local/share/jupyter
          key: jupyter-${{ runner.os }}-${{ hashFiles('requirements.txt', 'notebooks/*.ipynb') }}
          restore-keys: |
            jupyter-${{ runner.os }}-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert

      - name: Validate Jupyter notebooks
        run: |
          echo "Validating notebook syntax..."
          notebook_count=$(find notebooks -name "*.ipynb" | wc -l)
          echo "Found $notebook_count notebooks"
          # Quick syntax validation only (no execution to save time)
          find notebooks -name "*.ipynb" -type f | head -3 | xargs -I {} python -c "import json; json.load(open('{}'))" || echo "Some notebooks may have syntax issues"

      - name: Repository statistics
        run: |
          echo "Repository Statistics:"
          echo "- Total notebooks: $(find notebooks -name '*.ipynb' | wc -l)"
          echo "- Total LaTeX files: $(find . -name '*.tex' | wc -l)"
          echo "- Total PDF files: $(find . -name '*.pdf' | wc -l)"
          echo "- Categories: $(ls -1 | grep -E '^(basics|maths|supervised|neural-networks|advanced|unsupervised)$' | wc -l)"

      - name: Check for broken links in slides
        run: |
          echo "Checking slide references..."
          grep -r "includegraphics\|input\|include" . --include="*.tex" | head -10 || echo "No LaTeX references found"

  deploy:
    runs-on: ubuntu-latest
    needs: validate-and-build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          cache: true

      - name: Build and deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deployment complete
        run: |
          echo "Website deployed successfully!"
          echo "Available at: https://$(echo $GITHUB_REPOSITORY | cut -d'/' -f1).github.io/$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)/"