on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches:
      - master
      - main

name: Build & Deploy ML Course Materials

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python  
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Validate repository structure
        run: |
          cd $GITHUB_WORKSPACE
          echo "Working directory: $(pwd)"
          echo "Python version: $(python --version)"
          echo "Testing file existence:"
          test -f tests/test_structure.py && echo "✅ tests/test_structure.py exists" || echo "❌ tests/test_structure.py missing"
          test -f tests/test_graphics_paths.py && echo "✅ tests/test_graphics_paths.py exists" || echo "❌ tests/test_graphics_paths.py missing"
          echo "Running tests with explicit paths:"
          python ./tests/test_structure.py
          python ./tests/test_graphics_paths.py
          python ./tests/test_notebook_paths.py
          python ./tests/test_notebook_conventions.py
          python ./tests/test_slide_conventions.py
          python ./tests/test_missing_pdfs.py

      - name: Repository statistics
        run: |
          echo "Repository Statistics:"
          echo "- Total notebooks: $(find notebooks -name '*.ipynb' | wc -l)"
          echo "- Total LaTeX files: $(find . -name '*.tex' | wc -l)"
          echo "- Total PDF files: $(find . -name '*.pdf' | wc -l)"
          echo "- Categories: $(ls -1 | grep -E '^(basics|maths|supervised|neural-networks|advanced|unsupervised)$' | wc -l)"

      - name: Check for broken links in slides
        run: |
          echo "Checking slide references..."
          grep -r "includegraphics\|input\|include" . --include="*.tex" | head -10 || echo "No LaTeX references found"

  deploy:
    runs-on: ubuntu-latest
    needs: validate-and-build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          cache: true

      - name: Build and deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deployment complete
        run: |
          echo "Website deployed successfully!"
          echo "Available at: https://$(echo $GITHUB_REPOSITORY | cut -d'/' -f1).github.io/$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)/"