on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches:
      - master
      - main

name: Build & Deploy ML Course Materials

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python  
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      
  deploy:
    runs-on: ubuntu-latest
    needs: validate-and-build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          cache: true

      - name: Build and deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deployment complete
        run: |
          echo "Website deployed successfully!"
          echo "Available at: https://$(echo $GITHUB_REPOSITORY | cut -d'/' -f1).github.io/$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)/"
