name: Repository Structure Validation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate-structure:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Validate repository structure
      run: |
        python test_structure.py
        
    - name: Report structure violations
      if: failure()
      run: |
        echo "::error::Repository structure validation failed. Please check the violations above and run the suggested fixes."